# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/ruby/tags/
image: "rails:v23"

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
services:
#  - postgres:latest
#  - nginx:latest

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  - ruby -v
  - npm -v
  - node -v
  - gem source
#  - bundle config mirror.https://rubygems.org https://gems.ruby-china.org
#  - npm i
#  - gem sources --add https://ruby.taobao.org/ --remove https://gems.ruby-china.org/
#  - bundle config mirror.https://rubygems.org https://ruby.taobao.org

#  - gem install capistrano-harrow
#  - gem install childprocess -v '0.5.9'
#  - gem install rest-client -v '1.8.0'
#  - gem install unicorn -v '5.1.0'
#  - gem install spring -v '1.7.2'
#  - gem install i18n -v '0.7.0'

  - gem install cucumber-core -v '1.5.0'

  - locale
  - export LANG=en_US.UTF-8
  - locale
#  - export LANGUAGE=en_US.UTF-8

  - bundle install #-j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby
  - rails -v

rails:
  stage: build
  script:
    - cap production setup
    - cap production deploy
#
#rspec:
#  stage: test
#  script:
#   - rspec